name: CI

on: push

jobs:
  ci:
    name: Main pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6

      - name: Test
        uses: go test -v ./...

      - name: Build
        uses: gi build -v ./...
