name: CI

on: push

jobs:

  ci:
    name: Push pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Clean up previous builds
        run: rm -rf cmd/*

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
